---
apiVersion: v1
kind: Service
metadata:
  name: locust-server
  labels:
    app: locust-server
spec:
  type: NodePort
  ports:
  - name: master-web
    port: 80
    targetPort: http
    nodePort: 0
    protocol: TCP
  selector:
    app: locust-server
  sessionAffinity: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-server
  labels:
    app: locust-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: locust-server
    spec:
      containers:
      - name: locust-server
        image: "inikolaev/locust-server:latest"
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 512Mi
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - AUDIT_WRITE
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - MKNOD
            - NET_BIND_SERVICE
            - NET_RAW
            - SETFCAP
            - SETGID
            - SETPCAP
            - SETUID
            - SYS_CHROOT
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
